# Конфигурация SapphireRegionBlocks от DenaryDev
# Сделано на основе кода RegionBlocks от qKing12
# Сделано специально для сервера ActivMine

# Регионы
regions:
  # Название региона из WorldGuard
  # Можно указывать несколько регионов, разделяя их ;
  # Например: farm или farm;farm2;farm3
  farm;farm2;farm3;farm4:
    # ID блока в формате <material> или <material:tags>
    wheat[age=7]:
      # Время регенерации или диапазон времени
      # в формате <min>-<max> в секундах
      # Установите -1, чтобы блок не регенерировался
      # Обязательный параметр
      regen-time: 20-40
      # Проверять ли теги этого блока при регенерации?
      # Можно удалить (по умолчанию теги блоков не будут проверяться)
      check-block-tags: true
      # Временный блок
      # Работает, только если включено use-temporary-block
      # Можно удалить (по умолчанию временный блок не будет использоваться)
      temp-block: "wheat[age=1]"

    potatoes[age=7]:
      regen-time: 20-40
      check-block-tags: true
      temp-block: "potatoes[age=1]"
    carrots[age=7]:
      regen-time: 20-40
      temp-block: "carrots[age=1]"
    beetroots[age=3]:
      regen-time: 20-40
      check-block-tags: true
      temp-block: "beetroots[age=1]"

  mine:
    coal_ore:
      regen-time: 20
      temp-block: "cobblestone"
    iron_ore:
      regen-time: 35
      temp-block: "cobblestone"
    gold_ore:
      regen-time: 50
      temp-block: "cobblestone"

    stone:
      regen-time: 15
      temp-block: "cobblestone"
    cobblestone:
      regen-time: 10
      temp-block: "bedrock"

  forest:
    oak_log:
      regen-time: 6
    spruce_log:
      regen-time: 6
    birch_log:
      regen-time: 6
    dark_oak_log:
      regen-time: 6
    acacia_log:
      regen-time: 6
    jungle_log:
      regen-time: 6
    oak_leaves:
      regen-time: 6
    spruce_leaves:
      regen-time: 6
    birch_leaves:
      regen-time: 6
    dark_oak_leaves:
      regen-time: 6
    acacia_leaves:
      regen-time: 6
    jungle_leaves:
      regen-time: 6

  pumpkins-melons:
    pumpkin:
      regen-time: 20-40
    melon:
      regen-time: 20-40
